-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 21:02:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asistencias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asistencias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asistencias` DEFAULT CHARACTER SET utf8 ;
USE `asistencias` ;

-- -----------------------------------------------------
-- Table `asistencias`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`area` (
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`sindicato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`sindicato` (
  `idsindicato` INT NOT NULL,
  `sindicato` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idsindicato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`plaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`plaza` (
  `noplaza` VARCHAR(45) NOT NULL,
  `plaza` VARCHAR(45) NOT NULL,
  `sindicato_idsindicato` INT NOT NULL,
  PRIMARY KEY (`noplaza`),
  INDEX `fk_plaza_sindicato1_idx` (`sindicato_idsindicato` ASC),
  CONSTRAINT `fk_plaza_sindicato1`
    FOREIGN KEY (`sindicato_idsindicato`)
    REFERENCES `asistencias`.`sindicato` (`idsindicato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`grupo_organico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`grupo_organico` (
  `idgrupo_organico` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idgrupo_organico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`categoria` (
  `idcategoria` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `plaza_noplaza` VARCHAR(45) NOT NULL,
  `grupo_organico_idgrupo_organico` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_plaza1_idx` (`plaza_noplaza` ASC),
  INDEX `fk_categoria_grupo_organico1_idx` (`grupo_organico_idgrupo_organico` ASC),
  CONSTRAINT `fk_categoria_plaza1`
    FOREIGN KEY (`plaza_noplaza`)
    REFERENCES `asistencias`.`plaza` (`noplaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_grupo_organico1`
    FOREIGN KEY (`grupo_organico_idgrupo_organico`)
    REFERENCES `asistencias`.`grupo_organico` (`idgrupo_organico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`turno` (
  `idturno` INT NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  `turnocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idturno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`subcategoria` (
  `idsubcategoria` INT NOT NULL,
  `subcategoria` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idsubcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`empleado` (
  `RPE` VARCHAR(5) NOT NULL,
  `no_tarjeta` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `area_area` VARCHAR(45) NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `turno_idturno` INT NOT NULL,
  `subcategoria_idsubcategoria` INT NOT NULL,
  PRIMARY KEY (`RPE`),
  INDEX `fk_empleado_area1_idx` (`area_area` ASC),
  INDEX `fk_empleado_categoria1_idx` (`categoria_idcategoria` ASC),
  INDEX `fk_empleado_turno1_idx` (`turno_idturno` ASC),
  INDEX `fk_empleado_subcategoria1_idx` (`subcategoria_idsubcategoria` ASC),
  CONSTRAINT `fk_empleado_area1`
    FOREIGN KEY (`area_area`)
    REFERENCES `asistencias`.`area` (`area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `asistencias`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_turno1`
    FOREIGN KEY (`turno_idturno`)
    REFERENCES `asistencias`.`turno` (`idturno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_subcategoria1`
    FOREIGN KEY (`subcategoria_idsubcategoria`)
    REFERENCES `asistencias`.`subcategoria` (`idsubcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`asistencia` (
  `empleado_RPE` VARCHAR(5) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Dispositivo` VARCHAR(45) NOT NULL,
  `Punto del evento` VARCHAR(45) NOT NULL,
  `Verificacion` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Evento` VARCHAR(45) NOT NULL,
  `Notas` VARCHAR(45) NOT NULL,
  INDEX `fk_asistencia_empleado1_idx` (`empleado_RPE` ASC),
  CONSTRAINT `fk_asistencia_empleado1`
    FOREIGN KEY (`empleado_RPE`)
    REFERENCES `asistencias`.`empleado` (`RPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`cargo` (
  `cargo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencias`.`superusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencias`.`superusers` (
  `rpe` VARCHAR(5) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `cargo_cargo` VARCHAR(30) NOT NULL,
  `area_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rpe`),
  INDEX `fk_superusers_cargo1_idx` (`cargo_cargo` ASC),
  INDEX `fk_superusers_area1_idx` (`area_area` ASC),
  CONSTRAINT `fk_superusers_cargo1`
    FOREIGN KEY (`cargo_cargo`)
    REFERENCES `asistencias`.`cargo` (`cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_superusers_area1`
    FOREIGN KEY (`area_area`)
    REFERENCES `asistencias`.`area` (`area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
